name: MFEplugin
version: '1.0-Main'
main: humanusas.mfeplugin.MFEplugin
api-version: '1.20'
authors: [HuMaNusas]
description: Economic Plugin special for MineFinity! Yepi
commands:
  pay:
    description: Команда позволяющая пополнить свой или чужой баланс.
  balance:
    description: Команда позволяющая посмотреть свой баланс.
  withdraw:
    description: Команда позволяющая снять деньги со своего счёта.
  menu:
    description: Меню банкомата